### ISSUE TITLE
Data Diversity Matters for Robust Instruction Tuning

### ISSUE THREAD

**Issue by Dahoas** [Dahoas/QDSyntheticData#153]
- Paper name: Data Diversity Matters for Robust Instruction Tuning
- ArXiv Link :https://arxiv.org/abs/2311.14736

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by reshinthadithyan** [comment]
I'll take this.

**Comment by Dahoas** [comment]
This was already closed by #165
