### ISSUE TITLE
StarCoder2-Instruct

### ISSUE THREAD

**Issue by kanishkg** [Dahoas/QDSyntheticData#190]
- Paper name: StarCoder2-Instruct: Fully Transparent and Permissive Self-Alignment for Code Generation
- Blog Link: https://huggingface.co/blog/sc2-instruct
<img width="758" alt="Screenshot 2024-04-29 at 8 24 45 PM" src="https://github.com/Dahoas/QDSyntheticData/assets/17785540/1ba4bd97-3022-4b94-8f4b-b6f92ba38ca3">

**Comment by reshinthadithyan** [comment]
https://github.com/Dahoas/QDSyntheticData/pull/192
