### ISSUE TITLE
Text Quality-Based Pruning for Efficient Training of Language Models

### ISSUE THREAD

**Issue by Dahoas** [Dahoas/QDSyntheticData#217]
- Paper name: Text Quality-Based Pruning for Efficient Training of Language Models
- ArXiv Link: https://arxiv.org/abs/2405.01582

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by maia-iyer** [comment]
I'll take this one!
