### ISSUE TITLE
LMD3: Language Model Data Density Dependence

### ISSUE THREAD

**Issue by Dahoas** [Dahoas/QDSyntheticData#228]
- Paper name: LMD3: Language Model Data Density Dependence
- ArXiv Link: https://arxiv.org/abs/2405.06331

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by alon-albalak** [comment]
I'll take this one!
