### ISSUE TITLE
WizardMath: Empowering Mathematical Reasoning for Large Language Models via Reinforced Evol-Instruct

### ISSUE THREAD

**Issue by Dahoas** [Dahoas/QDSyntheticData#238]
- Paper name: WizardMath: Empowering Mathematical Reasoning for Large Language Models via Reinforced Evol-Instruct
- ArXiv Link: https://arxiv.org/abs/2308.09583

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by srishti-git1110** [comment]
I'll take this one.
