### ISSUE TITLE
Common 7B Language Models Already Possess Strong Math Capabilities

### ISSUE THREAD

**Issue by kanishkg** [Dahoas/QDSyntheticData#301]
- Paper name: Common 7B Language Models Already Possess Strong Math Capabilities
- ArXiv Link: https://arxiv.org/abs/2403.04706

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by srishti-git1110** [comment]
i'll take this.
