### ISSUE TITLE
Scaling Synthetic Data Creation with 1,000,000,000 Personas

### ISSUE THREAD

**Issue by Dahoas** [Dahoas/QDSyntheticData#310]
- Paper name: Scaling Synthetic Data Creation with 1,000,000,000 Personas
- ArXiv Link: https://arxiv.org/pdf/2406.20094

To close this issue open a PR with a paper report using the provided [report template](https://github.com/Dahoas/QDSyntheticData/blob/main/papers/paper_example.md).

**Comment by giove91** [comment]
@Dahoas The link to the report template is broken!
